# Generated by Django 2.1.5 on 2020-01-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('shorten_id', models.SlugField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('original_url', models.URLField()),
            ],
        ),
    ]
