# Generated by Django 2.1.5 on 2020-01-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortnerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
